### PR TITLE
multiple class available

### PR DESCRIPTION
**Pull request by namnn**

### CODE REVIEW

**Comment by KevCJones** [comment]
Really happy you've taken the time to contribute. 👍 
For the sake of documenting this change, could you just write in the description a small bit about `how` and `when` you might choose to leverage this capability.  Just so i understand it myself too but also so we can add it to the README.md too.

**Comment by namnn** [comment]
Ideally yes it would make the code more neat to have one class added to the wrapper or body.

My usecase is a little bit speacial as I already have a css file, which conflict with your css. So I didn't include yours in angular-cli but it misses something like backdrop.

Then I discover my css file has a class for backdrop, and I cannot give away class 'in' for wrapperClass, which eventually make me create another class for both backdrop and opacity.

**Comment by KevCJones** [comment]
True enough, it leaves it open, it has no side effects. Thanks for the contribution.

**Comment by namnn** [comment]
thanks, great library btw

**Pull request merged**
