### PR TITLE
Fixing issues with #69, @HostListener does not work in modal context

### PR DESCRIPTION
**Pull request by yadue**

### CODE REVIEW

**Comment by KevCJones** [comment]
Thanks for this, will review today and merge if all is well

**Comment by KevCJones** [comment]
Works nicely in my demo tests 👍

**Comment by yadue** [comment]
Hey @KevinCJones, thanks for merging, could you push package to npm? Thanks in advance.

**Comment by KevCJones** [comment]
I thought I did last night, check the latest patch. 👍

**Comment by yadue** [comment]
@KevCJones Sounds like it's not yet there:
https://www.npmjs.com/package/ngx-simple-modal?activeTab=versions

**Comment by KevCJones** [comment]
Intetesting, I'll check when I start work in an hour

**Pull request merged**
